name: Arduino CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.2
        with:
          version: 0.34.3

      - name: Install ESP8266 core
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266

      - name: Compile Sketch
        run: |
          arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2 sensor_ketinggian_air/sensor_ketinggian_air.ino

      - name: Run Lint or Format Check (Opsional)
        run: echo "Add format or lint check here if needed"
